#!/bin/bash

# Variables
RG_NAME="MonGroupeRessources"
LOCATION="eastus"
VNET_NAME="MonVNet"
SUBNET_NAME="MonSubnet"
IP_NAME="MonIPPublique"
NIC_NAME="MonNIC"
VM_NAME="MaVM"
VM_SIZE="Standard_DS1_v2"
ADMIN_USER="azureuser"
ADMIN_PASS="MotDePasse123!"
IMAGE="Win2019Datacenter"

# Se connecter à Azure
az login

# Créer le groupe de ressources
az group create --name $RG_NAME --location $LOCATION

# Créer VNet et Subnet
az network vnet create \
  --resource-group $RG_NAME \
  --name $VNET_NAME \
  --address-prefix 10.0.0.0/16 \
  --subnet-name $SUBNET_NAME \
  --subnet-prefix 10.0.1.0/24

# Créer IP publique
az network public-ip create \
  --resource-group $RG_NAME \
  --name $IP_NAME \
  --allocation-method Dynamic

# Créer NIC
az network nic create \
  --resource-group $RG_NAME \
  --name $NIC_NAME \
  --vnet-name $VNET_NAME \
  --subnet $SUBNET_NAME \
  --public-ip-address $IP_NAME

# Créer la VM
az vm create \
  --resource-group $RG_NAME \
  --name $VM_NAME \
  --nics $NIC_NAME \
  --image $IMAGE \
  --admin-username $ADMIN_USER \
  --admin-password $ADMIN_PASS \
  --size $VM_SIZE \
  --location $LOCATION \
  --output table

# Ouvrir le port RDP pour Windows (ou 22 pour SSH Linux)
az vm open-port --port 3389 --resource-group $RG_NAME --name $VM_NAME
